### ISSUE TITLE
Modify the wrapper to use the openJDK instead of oracle JDK

### ISSUE THREAD

**Issue by Swissbite** [vjkoskela/jdk-wrapper#26]
Oracle changed the lincense and the downloading pages, so there is no way to download the current JDK Versions (8+) via the Oracle web page. Instead, I would suggest to use the openJDK reference implementation to be used as source.

**Comment by vjkoskela** [comment]
This version of the jdk-wrapper is no longer supported. However, the functionality you are looking for already exists in its replacement: 

https://github.com/KoskiLabs/jdk-wrapper
